server:
  port: 8080

spring:
  application:
    name: shop-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  thymeleaf:
    cache: false

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: true
